<?php 
/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );

/**
* @package jmailunsubscribe
*/
class JMailUnsubscribeHelper {
	function checkCategories() {
	  global $mainframe ;
	  $db =& JFactory::getDBO();
	  $db->setQuery( "SELECT * FROM #__categories WHERE `section`='com_jmailunsubscribe'" ) ;
	  $rows = $db->loadAssocList() ;
	  if(empty($rows)) {
			$mainframe->enqueueMessage( JText::_( 'You have no categories configured yet' ), 'notice' ) ;
	  	return false ;
	  }
	  return true ;
	}
}