<?php
/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined ( '_JEXEC' ) or die ( 'Restricted access' );

jimport ( 'joomla.application.component.controller' );
require_once (JPATH_COMPONENT . DS . 'helpers' . DS . 'helper.php');

/**
 * JMailUnsubscribe Controller
 *
 * @package JMailUnsubscribe
 */
class JMailUnsubscribeController extends JController {
	function __construct() {
		parent::__construct ();
		// Register Extra tasks
		$this->registerTask ( 'add', 'display' );
		$this->registerTask ( 'edit', 'display' );
	}
	function display() {
		switch ($this->getTask ()) {
			case 'add' :
				{
					JRequest::setVar ( 'hidemainmenu', 1 );
					JRequest::setVar ( 'layout', 'form' );
					JRequest::setVar ( 'view', 'item' );
					JRequest::setVar ( 'edit', false );
					// Checkout the item
				}
				break;
			case 'edit' :
				{
					JRequest::setVar ( 'hidemainmenu', 1 );
					JRequest::setVar ( 'layout', 'form' );
					JRequest::setVar ( 'view', 'item' );
					JRequest::setVar ( 'edit', true );
				}
				break;
		}
		parent::display ();
	}
	function store() {
		$post = JRequest::get ( 'post' );
		$cid = JRequest::getVar ( 'cid', array (
				0 
		), 'post', 'array' );
		$post ['id'] = ( int ) $cid [0];
		$this->id = $post ['id'];
		$model = $this->getModel ( 'item' );
		if ($model->store ( $post )) {
			$alert_data = $model->getData ();
			$user_email = $alert_data->user_email;
			$alert_name = $alert_data->alert_name;
			JMailUnsubscribeHelper::mailUnsubscribeConfirmation($user_email, $alert_name);
			$this->msg = JText::_ ( 'Item Saved' );
		} else {
			$this->msg = JText::_ ( 'Error Saving Item' );
		}
	}
	function save() {
		$this->store ();
		$link = 'index.php?option=com_jmailunsubscribe';
		$this->setRedirect ( $link, $this->msg );
	}
	function apply() {
		$this->store ();
		$link = 'index.php?option=com_jmailunsubscribe&view=item&task=edit&cid[]=' . $this->id;
		$this->setRedirect ( $link, $this->msg );
	}
	function cancel() {
		$model = $this->getModel ( 'item' );
		$this->setRedirect ( 'index.php?option=com_jmailunsubscribe' );
	}
	function orderup() {
		$model = $this->getModel ( 'item' );
		$model->move ( - 1 );
		$this->setRedirect ( 'index.php?option=com_jmailunsubscribe' );
	}
	function orderdown() {
		$model = $this->getModel ( 'item' );
		$model->move ( 1 );
		$this->setRedirect ( 'index.php?option=com_jmailunsubscribe' );
	}
	function saveorder() {
		$cid = JRequest::getVar ( 'cid', array (), 'post', 'array' );
		$order = JRequest::getVar ( 'order', array (), 'post', 'array' );
		JArrayHelper::toInteger ( $cid );
		JArrayHelper::toInteger ( $order );
		$model = $this->getModel ( 'item' );
		$model->saveorder ( $cid, $order );
		$msg = 'New ordering saved';
		$this->setRedirect ( 'index.php?option=com_jmailunsubscribe', $msg );
	}
}