<?php 

/**
 * Joomla! 1.5 component JMailUnsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-152014-12-15
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
function com_uninstall() {
?>
<div class="header">The administator component JMailUnsubscribe was sucessfully removed</div>
<?php
  }
?>