<?php
/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined ( '_JEXEC' ) or die ( 'Restricted access' );

jimport ( 'joomla.application.component.view' );
/**
 * HTML View class for the jmailunsubscribe component
 *
 * @static
 *
 * @package JMailUnsubscribe
 *         
 */
class JMailUnsubscribeViewItem extends JView {
	var $_item;
	function display($tpl = null) {
		global $mainframe;
		// get the item
		$this->_item = & $this->get ( 'data' );
		if ($this->getLayout () == 'form') {
			$this->_displayForm ( $tpl );
			return;
		}
		parent::display ( $tpl );
	}
	function _displayForm($tpl) {
		global $mainframe, $option;
		$db = & JFactory::getDBO ();
		$uri = & JFactory::getURI ();
		$user = & JFactory::getUser ();
		$model = & $this->getModel ( 'item' );
		$lists = array ();
		// get the item
		$item = & $this->get ( 'data' );
		parent::display ( $tpl );
	}
}
