<?php
/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined ( '_JEXEC' ) or die ( 'Restricted access' );

jimport ( 'joomla.application.component.view' );
/**
 * HTML View class for the jmailunsubscribe component
 *
 * @static
 *
 * @package JMailUnsubscribe
 *         
 */
class JMailUnsubscribeViewJMailUnsubscribe extends JView {
	function display($tpl = null) {
		global $mainframe, $option;
		$db = & JFactory::getDBO ();
		$uri = & JFactory::getURI ();
		$filter_state = $mainframe->getUserStateFromRequest( $option.'filter_state', 'filter_state', '', 'word' );
		$filter_order = $mainframe->getUserStateFromRequest ( $option . 'filter_order', 'filter_order', 'user_name', 'cmd' );
		$filter_order_Dir = $mainframe->getUserStateFromRequest ( $option . 'filter_order_Dir', 'filter_order_Dir', '', 'word' );
		$search = $mainframe->getUserStateFromRequest ( $option . 'search', 'search', '', 'string' );
		$search = JString::strtolower ( $search );
		// Get data from the model
		$items = & $this->get ( 'Data' );
		$total = & $this->get ( 'Total' );
		$pagination = & $this->get ( 'Pagination' );

		// state filter
		if ($filter_state == 'U') {	// U means Unsubscribed
			$lists ['state'] = "<select name=\"filter_state\" id=\"filter_state\" class=\"inputbox\" size=\"1\" onchange=\"submitform();\"><option value=\"\" >- Select Alert Option -</option><option value=\"S\" >Subscribed</option><option value=\"U\" selected=\"selected\">Unsubscribed</option></select>";
		} else if ($filter_state == 'S') {
			$lists ['state'] = "<select name=\"filter_state\" id=\"filter_state\" class=\"inputbox\" size=\"1\" onchange=\"submitform();\"><option value=\"\" >- Select Alert Option -</option><option value=\"S\" selected=\"selected\">Subscribed</option><option value=\"U\" >Unsubscribed</option></select>";
		} else {
			$lists ['state'] = "<select name=\"filter_state\" id=\"filter_state\" class=\"inputbox\" size=\"1\" onchange=\"submitform();\"><option value=\"\"  selected=\"selected\">- Select Alert Option -</option><option value=\"S\" >Subscribed</option><option value=\"U\" >Unsubscribed</option></select>";
		}
		
		// table ordering
		$lists ['order_Dir'] = $filter_order_Dir;
		$lists ['order'] = $filter_order;
		// search filter
		$lists ['search'] = $search;
		$this->assignRef ( 'user', JFactory::getUser () );
		$this->assignRef ( 'lists', $lists );
		$this->assignRef ( 'items', $items );
		$this->assignRef ( 'pagination', $pagination );
		
		parent::display ( $tpl );
	}
}