<?php
/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined ( '_JEXEC' ) or die ( 'Restricted access' );
$editor = & JFactory::getEditor ();

JHTML::_ ( 'behavior.tooltip' );
JHTML::_ ( 'behavior.modal' );
jimport ( 'joomla.html.pane' );
$document = & JFactory::getDocument ();
$document->addScriptDeclaration ( "function submitbutton(task) {
	var text = " . $editor->getContent ( 'text' ) . "
	if (task == 'save') {
		" . $editor->save ( 'text' ) . "
		submitform(task);
	}
}" );

// Set toolbar items for the page
$edit = JRequest::getVar ( 'edit', true );
$text = ! $edit ? JText::_ ( 'New' ) : JText::_ ( 'Edit' );
JToolBarHelper::title ( JText::_ ( 'Item' ) . ': <small>[ ' . $text . ' ]</small>' );
JToolBarHelper::save ();
if (! $edit) {
	JToolBarHelper::cancel ();
} else {
	JToolBarHelper::apply ();
	JToolBarHelper::cancel ( 'cancel', 'Close' );
}
?>
<script language="javascript" type="text/javascript">
<!--
	function submitbutton(pressbutton) {
  	var form = document.adminForm;
		if (pressbutton == 'cancel') {
  		submitform( pressbutton );
			return;
		}
		// do field validation
		if (form.title.value == ""){
			alert( "<?php echo JText::_( 'Please give a title', true ); ?>" );
		} else if (form.catid.value == "0"){
			alert( "<?php echo JText::_( 'Please select a category', true ); ?>" );
		} else {
			submitform( pressbutton );
		}
	}
	
	
-->
</script>

<form action="index.php" method="post" name="adminForm" id="adminForm">
	<table cellspacing="0" cellpadding="0" border="0" width="100%">
		<tr>
			<td valign="top">
				<table class="adminform">
					<tbody>
						<tr>
							<td><label for="title"><?php echo JText::_( 'Title' ); ?>:</label></td>
							<td><input class="text_area" type="text" name="title" id="title"
								size="32" maxlength="250"
								value="<?php echo $this->item->title;?>" /></td>
							<td><label><?php echo JText::_( 'Published' ); ?>:</label></td>
							<td><label><?php echo $this->lists['published']; ?></label></td>
						</tr>
						<tr>
							<td><label for="alias"><?php echo JText::_( 'Alias' ); ?>:</label></td>
							<td><input class="text_area" type="text" name="alias" id="alias"
								size="32" maxlength="250"
								value="<?php echo $this->item->alias;?>" /></td>
							<td><label for="ordering"><?php echo JText::_( 'Ordering' ); ?>:</label></td>
							<td><?php echo $this->lists['ordering']; ?></td>
						</tr>
						<tr>
							<td><label for="catid"><?php echo JText::_( 'Category' ); ?>:</label></td>
							<td><?php echo $this->lists['catid']; ?></td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
					</tbody>
				</table>
				<table class="adminform">
					<tbody>
						<tr>
							<td width="100" align="right"><label for="alertid"><?php echo JText::_( 'Alertid' ) ?>:</label></td>
							<td><input class="text_area" type="text" name="alertid"
								id="alertid" size="32" maxlength="250"
								value="<?php echo $this->item->alertid ?>" /></td>
						</tr>
						<tr>
							<td width="100" align="right"><label for="subscribed"><?php echo JText::_( 'Subscribed' ) ?>:</label></td>
							<td><input class="text_area" type="text" name="subscribed"
								id="subscribed" size="32" maxlength="250"
								value="<?php echo $this->item->subscribed ?>" /></td>
						</tr>
						<tr>
							<td width="100" align="right"><label for="pluginssubscribedto"><?php echo JText::_( 'Pluginssubscribedto' ) ?>:</label></td>
							<td><input class="text_area" type="text"
								name="pluginssubscribedto" id="pluginssubscribedto" size="32"
								maxlength="250"
								value="<?php echo $this->item->pluginssubscribedto ?>" /></td>
						</tr>


					</tbody>
				</table>
			</td>
			<td width="320" valign="top" style="padding: 7px 0pt 0pt 5px;">
				<table width="100%"
					style="border: 1px dashed silver; padding: 5px; margin-bottom: 10px;">
					<tbody>
						<tr>
							<td><strong><?php echo JText::_( 'Article ID' ) ?></strong></td>
							<td><?php  echo $this->item->id?></td>
						</tr>
						<tr>
							<td><strong><?php echo JText::_( 'Hits' ); ?></strong></td>
							<td><?php  echo $this->item->hits?></td>
						</tr>
						<tr>
							<td><strong><?php echo JText::_( 'Created' ); ?></strong></td>
							<td><?php  echo $this->item->created?></td>
						</tr>
						<tr>
							<td><strong><?php echo JText::_( 'Created by' ); ?></strong></td>
							<td><?php  echo $this->item->created_by_alias?></td>
						</tr>
					</tbody>
				</table>
				<div id="content-pane" class="pane-sliders">
					<div class="panel">
						<h3 id="detail-page" class="title jpane-toggler"><?php echo JText::_( 'Parameters' ); ?></h3>
						<div class="slider content"><?php echo $this->params->render();?></div>
					</div>
				</div>
			</td>
		</tr>
	</table>
	<input type="hidden" name="option" value="com_jmailunsubscribe" /> <input
		type="hidden" name="cid[]" value="<?php echo $this->item->id; ?>" /> <input
		type="hidden" name="task" value="" />
</form>
<div>
	Diese Komponente wurde mit <a href="http://joodo.hopper-intermedia.de">jooDo!</a>
	erstellt. Ein Service von <a href="http://hopper-intermedia.de">hopper
		intermedia</a>.
</div>