<?php
/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined ( '_JEXEC' ) or die ( 'Restricted access' );
$editor = & JFactory::getEditor ();

JHTML::_ ( 'behavior.tooltip' );
JHTML::_ ( 'behavior.modal' );
jimport ( 'joomla.html.pane' );
$document = & JFactory::getDocument ();
$document->addScriptDeclaration ( "function submitbutton(task) {
	var text = " . $editor->getContent ( 'text' ) . "
	if (task == 'save') {
		" . $editor->save ( 'text' ) . "
		submitform(task);
	}
}" );

// Set toolbar items for the page
$edit = JRequest::getVar ( 'edit', true );
$text = ! $edit ? JText::_ ( 'New' ) : JText::_ ( 'Edit' );
JToolBarHelper::title ( JText::_ ( 'Item' ) . ': <small>[ ' . $text . ' ]</small>' );
JToolBarHelper::save ();
if (! $edit) {
	JToolBarHelper::cancel ();
} else {
	JToolBarHelper::apply ();
	JToolBarHelper::cancel ( 'cancel', 'Close' );
}
?>
<script language="javascript" type="text/javascript">

	function submitbutton(pressbutton) {
  	var form = document.adminForm;
		if (pressbutton == 'cancel') {
  		submitform( pressbutton );
			return;
		}
		// do field validation
		if (form.subscribed.value == ""){
			alert( "<?php echo JText::_( 'Please specify an option value', true ); ?>" );
		} else {
			submitform( pressbutton );
		}
	}
	
	

</script>

<form action="index.php" method="post" name="adminForm" id="adminForm">
	<table cellspacing="0" cellpadding="0" border="0" width="100%">
		<tr>
			<td valign="top">
				<table class="adminform">
					<tbody>
						<tr>
							<td width="100" align="right"><strong><?php echo JText::_( 'Alert id' ) ?>:</strong></td>
							<td><?php echo $this->_item->alert_id ?></td>
						</tr>
						<tr>
							<td width="100" align="right"><strong><label for="subscribed"><?php echo JText::_( 'Alert option' ) ?>:</label></strong></td>
							<td><input class="text_area" type="text" name="subscribed"
								id="subscribed" size="3" maxlength="3"
								value="<?php echo $this->_item->alert_option ?>" /></td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</table>
	<input type="hidden" name="option" value="com_jmailunsubscribe" /> <input
		type="hidden" name="cid[]" value="<?php echo $this->_item->alert_id; ?>" /> <input
		type="hidden" name="task" value="" />
</form>
