<?php

/**
 * Joomla! 1.5 component jmailunsubscribe
 * Code generated by : Joomla! 1.5 MVC Component Code Generator
 * http://www.hopper-intermedia.de
 * date generated: 2014-12-15
 * @version 0.8
 * @author Jean-Pierre Schnyder 
 * @package com_jmailunsubscribe
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined ( '_JEXEC' ) or die ( 'Restricted access' );

// Include library dependencies
jimport ( 'joomla.filter.input' );
/**
 * JMailUnsubscribe Item Table class
 * 
 * @package JMailUnsubscribe
 */
class TableItem extends JTable {
	/**
	 * Primary Key
	 *
	 * @var int
	 */
	var $id = null;
	/**
	 *
	 * @var int
	 */
	var $option = null;
	
	/**
	 * Constructor
	 *
	 * @param
	 *        	object Database connector object
	 */
	function __construct(& $db) {
		parent::__construct ( '#__email_alert', 'id', $db );
	}
	/**
	 * Overloaded bind function
	 *
	 * @acces public
	 * 
	 * @param array $hash
	 *        	named array
	 * @return null|string null is operation was satisfactory, otherwise returns an error
	 * @see JTable:bind
	 */
	function bind($array, $ignore = '') {
		if (key_exists ( 'params', $array ) && is_array ( $array ['params'] )) {
			$registry = new JRegistry ();
			$registry->loadArray ( $array ['params'] );
			$array ['params'] = $registry->toString ();
		}
		// get wysiwyg code
		
		return parent::bind ( $array, $ignore );
	}
	/**
	 * Overloaded check method to ensure data integrity
	 *
	 * @access public
	 * @return boolean True on success
	 */
	function check() {
		return true;
	}
}
